services:
  # --- PostgreSQL ---
  db:
    build: 
      dockerfile: Dockerfile.db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    container_name: gc-api
    restart: unless-stopped

    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}
      PG_PORT: ${PG_PORT}
      PG_HOST: db
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
      PG_DB: ${PG_DB}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    
    depends_on:
      db:
        condition: service_healthy
      
